spring:
  application:
    name: hrchatbot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    ollama:
      base-url: http://localhost:11434
      model: gemma3:4b
      chat:
        options:
          temperature: 0.4
          model: gemma3:4b
      embedding:
        options:
          model: mxbai-embed-large
    model:
      embedding: ollama
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

